# Uncomment the next line to define a global platform for your project

platform :ios, '14.0'
use_frameworks!
target 'CountryPicker_Example' do
#    pod 'CountryPickerSwift'
    pod 'CountryPickerSwift', :path => '../'

end

# Xcode 14.3 build fix
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end
